name       : shotwell
homepage   : https://wiki.gnome.org/Apps/Shotwell
version    : 0.23.5
release    : 7
source     :
    - https://download.gnome.org/sources/shotwell/0.23/shotwell-0.23.5.tar.xz : 07287405a8ff978e3b5095db1d28a115ef8c78a95be77eeb4ac7d7b95f0efa39
license    : LGPL-2.1
component  : multimedia.graphics
summary    : A digital photo organizer designed for the GNOME desktop environment
description: |
    A digital photo organizer designed for the GNOME desktop environment
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgphoto2)
    - pkgconfig(libraw)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - desktop-file-utils
    - vala
    - itstool
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
