name       : shotwell
version    : 0.22.0
release    : 1
source     :
    - https://download.gnome.org/sources/shotwell/0.22/shotwell-0.22.0.tar.xz : 01b192c5c1c188ecd11bfdb6143d8f177f313c7eab7fe320bd20ac3ca352f831
license    : LGPL-2.1
summary    : A digital photo organizer designed for the GNOME desktop environment
description: |
    A digital photo organizer designed for the GNOME desktop environment
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(gee-0.8)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(libraw1394)
    - pkgconfig(rest-0.7)
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
