name       : shotwell
homepage   : https://wiki.gnome.org/Apps/Shotwell
version    : 0.30.8
release    : 32
source     :
    - https://download.gnome.org/sources/shotwell/0.30/shotwell-0.30.8.tar.xz : 722d2ed2ffc843b150490d5e346395398b0b5f40dd706034fa3a70f30e00f5b8
license    : LGPL-2.1-or-later
component  : multimedia.graphics
summary    : A digital photo organizer designed for the GNOME desktop environment
description: |
    Shotwell is a digital photo manager designed for the GNOME desktop environment.  It allows you to import photos from disk or camera, organize them by keywords and events, view them in full-window or fullscreen mode, and share them with others via social networking and more.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(libgdata)
    - pkgconfig(libgphoto2)
    - pkgconfig(libraw)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - desktop-file-utils
    - vala
    - itstool
setup      : |
    %meson_configure -Dinstall-apport-hook=false
build      : |
    %ninja_build
install    : |
    %ninja_install
