name       : shotwell
homepage   : https://wiki.gnome.org/Apps/Shotwell
version    : 0.31.4
release    : 43
source     :
    - https://download.gnome.org/sources/shotwell/0.31/shotwell-0.31.4.tar.xz : b16f4f457c5f34c6fd9509d582f94635944142040cd952671febad93174fa2ef
license    : LGPL-2.1-or-later
component  : multimedia.graphics
summary    : A digital photo organizer designed for the GNOME desktop environment
description: |
    Shotwell is a digital photo manager designed for the GNOME desktop environment.  It allows you to import photos from disk or camera, organize them by keywords and events, view them in full-window or fullscreen mode, and share them with others via social networking and more.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(gee-0.8)
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(libgdata)
    - pkgconfig(libgphoto2)
    - pkgconfig(libraw)
    - pkgconfig(libsecret-1)
    - pkgconfig(libwebpdemux)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - desktop-file-utils
    - vala
    - itstool
setup      : |
    %meson_configure -Dinstall_apport_hook=false
build      : |
    %ninja_build
install    : |
    %ninja_install
