name       : shotwell
homepage   : https://wiki.gnome.org/Apps/Shotwell
version    : 0.32.0
release    : 44
source     :
    - https://download.gnome.org/sources/shotwell/0.32/shotwell-0.32.0.tar.xz : 1772b2fa1e7a5479d528028bc9a303f2855e1d959a5b3c917922e63a98a90b19
license    : LGPL-2.1-or-later
component  : multimedia.graphics
summary    : A digital photo organizer designed for the GNOME desktop environment
description: |
    Shotwell is a digital photo manager designed for the GNOME desktop environment.  It allows you to import photos from disk or camera, organize them by keywords and events, view them in full-window or fullscreen mode, and share them with others via social networking and more.
builddeps  :
    - pkgconfig(champlain-0.12)
    - pkgconfig(gee-0.8)
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(libgdata)
    - pkgconfig(libgphoto2)
    - pkgconfig(libportal)
    - pkgconfig(libraw)
    - pkgconfig(libsecret-1)
    - pkgconfig(libwebpdemux)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.1)
    - desktop-file-utils
    - vala
    - itstool
setup      : |
    %meson_configure -Dinstall_apport_hook=false
build      : |
    %ninja_build
install    : |
    %ninja_install
