name       : shotwell
homepage   : https://wiki.gnome.org/Apps/Shotwell
version    : 0.24.5
release    : 11
source     :
    - https://download.gnome.org/sources/shotwell/0.24/shotwell-0.24.5.tar.xz : 4936c2c8c63b701ac0cf15b7bd6619ee3241a6d08b4187f2475348642ff9c1fd
license    : LGPL-2.1
component  : multimedia.graphics
summary    : A digital photo organizer designed for the GNOME desktop environment
description: |
    A digital photo organizer designed for the GNOME desktop environment
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgphoto2)
    - pkgconfig(libraw)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - desktop-file-utils
    - vala
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
