name       : shotwell
version    : 0.23.0
release    : 4
source     :
    - https://download.gnome.org/sources/shotwell/0.23/shotwell-0.23.0.tar.xz : 1d64bf1456d4d955c8db69225a63e1f6b652ab91f3121a022486428799bbf1fd
license    : LGPL-2.1
component  : desktop.multimedia
summary    : A digital photo organizer designed for the GNOME desktop environment
description: |
    A digital photo organizer designed for the GNOME desktop environment
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(gexiv2)
    - pkgconfig(gnome-doc-utils)
    - pkgconfig(gstreamer-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libgphoto2)
    - pkgconfig(libraw)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - desktop-file-utils
    - vala
setup      : |
    ./configure --prefix=/usr
build      : |
    %make
install    : |
    %make_install
    rm $installdir/usr/share/glib-2.0/schemas/gschemas.compiled
    rm $installdir/usr/share/icons/hicolor/icon-theme.cache
